<?
require_once("admin/config/global.php");
if (!function_exists("GetSQLValueString")) {
function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  if (PHP_VERSION < 6) {
    $theValue = get_magic_quotes_gpc() ? stripslashes($theValue) : $theValue;
  }

  $theValue = function_exists("mysql_real_escape_string") ? mysql_real_escape_string($theValue) : mysql_escape_string($theValue);

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? doubleval($theValue) : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}
}

$id = $_GET['id'];
if(isset($_POST['sid'])){
	$id= $_POST['sid'];
}

$send_complete_email = false;
if(isset($_POST['update'])){
	
	 $updateSQL = sprintf("UPDATE sampleSets SET results_location=%s, comments=%s WHERE id=%s",
                       GetSQLValueString($_POST['results_location'], "text"),
                       GetSQLValueString($_POST['comments'], "text"),
                       GetSQLValueString($id, "int"));
					   //echo $updateSQL . "<BR>";
  	$Result1 = mysql_query($updateSQL) or die(mysql_error());
	
}else if(isset($_POST['complete'])){
	$q = "update sampleSets set status=(select id from statuses where status = \"Completed\"), date_reviewed = NOW(), reviewed_by=" . $_POST['supervisor_id'] . " where id=" . $id;
	mysql_query($q) or die (mysql_error());
	$send_complete_email = true;
}

$q = "select ss.id, ss.name, results_location, comments, priority, DATE_FORMAT(submission_date, '%c/%d/%Y') as sd, DATE_FORMAT(expected_completion_date, '%c/%d/%Y') as ecd, " .
					"DATE_FORMAT(date_analyzed, '%c/%d/%Y') as date_analyzed, submitted_by, " . 
					"(select CONCAT(first_name, ' ', SUBSTRING(last_name, 1, 1), '.') from staff_list where id=submitted_by) as sb, " . 
					"(select email from staff_list where id=submitted_by) as sb_email, " . 
					"analyzed_by, " . 
					"(select CONCAT(first_name, ' ', SUBSTRING(last_name, 1, 1), '.') from staff_list where id=analyzed_by) as ab, " .
					"(select count(*) as thatsit from samples s where s.sampleset_id=ss.id) as sample_count, " . 
					"(select first_name from staff_list where title='Supervisor' and mailing_list_id=sl.mailing_list_id) as supervisor_name, " .
					"(select email from staff_list where title='Supervisor' and mailing_list_id=sl.mailing_list_id) as supervisor_email, " .
					"(select id from staff_list where title='Supervisor' and mailing_list_id=sl.mailing_list_id) as supervisor_id, " .
					"status, (select status from statuses s where s.id=ss.status) as status_wd, mailing_list_id " .
					" from sampleSets ss, staff_list sl " .
					" where analyzed_by = sl.id and ss.id= " . $id; 

$ssq = mysql_query($q) or die(mysql_error());
$sampleSet = mysql_fetch_assoc($ssq);

$q = "SELECT id, sampleset_id, sample_id, name, characterization_requested, (select name from sample_characterizations sc where sc.id=s.characterization_requested) as cr, assay_performed, status, estimated_concentration, measured_concentration, ph, location, analyzed FROM samples s WHERE sampleset_id =" . $id;
$samples = mysql_query($q) or die (mysql_error());

$q = "select * from assays ";
$assays = mysql_query($q) or die (mysql_error());

if($send_complete_email){
	$email_query = "select first_name, last_name, email from staff_list where mailing_list_id in (select mailing_list_id from staff_list where id=" . $sampleSet['submitted_by'] . " or id=" . $sampleSet['analyzed_by'] . ")"; 
	$emails = mysql_query($email_query) or die (mysql_error());

	$email_text = "Dear " . $sampleSet['sb'] . ", <br><br>" . $sampleSet['supervisor_name'] . " has just completed the review of the sample list entitled " . $sampleSet['name'] . " that you submitted on " . $sampleSet['submission_date'] . ".<br><br>";
	$email_text .= "Please contact him if you have any questions.<br><br>";
	$email_text .= "This email has been automatically generated by the Dendreon Sample Submission Tracking Application.";
		
	// To send HTML mail, the Content-type header must be set
	$headers  = 'MIME-Version: 1.0' . "\r\n";
	$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
	
	// Additional headers
	//$headers .= 'To: Hector Ramos <ramoshf@gmail.com>' . "\r\n"; 	
	$headers .= 'From: DNDN Sample Tracking Application<noreply@dendreon.com>' . "\r\n";
	//$headers .= 'Bcc: birthdaycheck@example.com' . "\r\n";
	$headers .= 'Reply-To: noreply@dendreon.com' . "\r\n";
		
		
	$to = "";
	$i = 0;
	while($email = mysql_fetch_assoc($emails)){
		if($i++ > 0){
			$to .= ", ";
		}
		$to .= $email['email'];
	}
	if($Global['debug'] == true){$email_text .= "DEBUG: This email would have been sent to: " . $to; $to = $Global['debug_to']; 
	}
	mail($to, "Sample Set Reviewed and Completed", $email_text, $headers);
}
?>
<!DOCTYPE HTML>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Sample Set Review Page</title>
        <meta name="description" content="">
        <? if ($send_complete_email){ ?><meta http-equiv="refresh" content="3; url=<?= $Global['baseurl'] ?>"> <? } ?>
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory 
        <script src="DataTables-1.9.4/media/js/jquery.js"></script>-->
		<!--<script src="DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
        <link rel="stylesheet" type="text/css" href="DataTables-1.9.4/media/css/demo_page.css">
        <link rel="stylesheet" type="text/css" href="DataTables-1.9.4/media/css/demo_table.css">-->
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
        <!--
          Loading Handsontable (full distribution that includes all dependencies apart from jQuery)
      -->
          <script src="js/vendor/jquery-1.9.0.min.js"></script>
          <script src="jquery-handsontable-master/dist/jquery.handsontable.full.js"></script>
          <link rel="stylesheet" media="screen" href="jquery-handsontable-master/dist/jquery.handsontable.full.css">
 	
    <!-- for the dialog box 
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>-->
	<!-- more for dialog box -->
    <style>
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
</head>

<body>        
  <div role="content" class="clearfix">
    <header class="clearfix" style="padding: 0px; padding-bottom: 10px; margin-bottom: 10px;">
      <h1>Sample Set Review</h1>
      <h2>Sample Set Being Reviewed by <?= $sampleSet['sb'] ?></h2>
    </header>
        <script src="js/nav.js"></script>

	<? if($send_complete_email){ ?>
    <p>Thank you for reviewing the sample set <strong><?= $sampleSet['name'] ?></strong>.  You will now be redirected to the home page in 3 seconds...</p>
    <? } else { ?>
	<p>Sample Set: <strong><?= $sampleSet['name'] ?></strong></p>
    <form action="<?= $_SERVER['PHP_SELF'] ?>?id=<?= $id ?>" method="post">
    <input type="hidden" name="sid" value="<?= $id ?>"/>
    	<table>
        <tr><td>Results Location:</td><td><a href="file://<?= $sampleSet['results_location'] ?>" target="_blank"><?= $sampleSet['results_location'] ?></a></td></tr>
        <tr><td valign="top">Comments:</td><td><textarea name="comments" rows="5" cols="40"><?= $sampleSet['comments'] ?></textarea></td><td></td></tr>
        </table><br>
        <p><a href="sampleSetReview.php?id=<?= $id ?>"><img src="images/link_img.png" width="28" height="15" alt="link">Click here to get all the details of this sample set list.</a></p>
		<input type="submit" name="update" value="Save Changes" /> -or- <!-- onClick="$('#tableData').val(JSON.stringify($('#handsomeTable').data('handsontable').getData()));" -->
		<input type="submit" name="complete" value="Click here when you have Reviewed the Results and are Satisfied" /><br><BR>
	
    	Sample List:
    <? /*  ?>
        
        <p><input type="submit" name="startJob" value="Click here when you are ready to begin the analysis on these samples." /></p>
	
    	Sample List:
	<? }else{ ?>
    	<p>The status of this Sample set list is <strong><?= $sampleSet['status_wd'] ?></strong>.  As such, this page doesn't show any information about it.  Please see the sample set summary page <a href="sampleSetReview.php?id=<?= $id ?>"> here </a>.</p>
    <? */ ?>	
    <div id="handsomeTable">
              <? $data_str = "[";
                    while($r = mysql_fetch_assoc($samples)){
                        //colHeaders: ['Sample ID', 'Sample Name', 'Assay', 'EST. Conc., ug/mL', 'ph'],
                        if($data_str != "["){ $data_str .= ", ";}
						$data_str .= "[" . $r['id'] . ",'" . $r['sample_id'];
						$data_str .= "', '" . $r['name'] . "', '" . $r['cr'] . "', '";
							while($ass = mysql_fetch_assoc($assays)){
								if($ass['id'] == $r['assay_performed']){
									$data_str .= $ass['name'];
								}
						}
						mysql_data_seek($assays, 0);
						$data_str .= "', '" . $r['ph'] . "', '" . $r['estimated_concentration'] . "']";
                        } 
                    $data_str .= "]"; 
                    ?>
	</div>
	<input type="hidden" name="tableData" id="tableData">
	<input type="hidden" name="supervisor_id" value="<?= $sampleSet['supervisor_id'] ?>">
    </form>
    <? } ?>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
   
    <footer>
        &nbsp;
    </footer>
</div>
<script>
 var data = eval(<?= $data_str ?>);

			var container = $('#handsomeTable');
            container.handsontable({
             data: data,
              startRows: 8,
              startCols: 6,
			  rowHeaders: true,
  			  colHeaders: ['Sample Number', 'Sample Name', 'Characterization Requested', 'Assay', 'ph', 'EST. Conc.'],
			  minSpareCols: 0,
			  minSpareRows: 0,
              currentRowClassName: 'currentRow',
              currentColClassName: 'currentCol',
			  contextMenu: true,
  			manualColumnResize: true,
			  columns: [
			  		{data: 1, type: 'text', readOnly: true},
			  		{data: 2, type: 'text', readOnly: true},
			  		{data: 3, type: 'text', readOnly: true},
					{
						data: 4, 
						readOnly: true,
					  type: 'autocomplete',
					  source: [ <? $i = 0; while($a = mysql_fetch_assoc($assays)){
						  						if($i++ > 0){echo ", ";}
						  						echo "\"" . $a['name'] . "\"";
					  						} ?>
						  		]
					},
			  		{data: 5, type: 'text', readOnly: true},
			  		{data: 6, type: 'text', readOnly: true}
			  		//{data: 7, type: 'checkbox'}
				]
			});
</script>
</body>
</html>
<?
mysql_free_result($ssq);
mysql_free_result($samples);
mysql_free_result($assays);
?>